name: build

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: dlist-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Checkout dist repo
        uses: actions/checkout@v4
        with:
          ref: web-dist
          path: web-dist
          fetch-depth: 0

      - name: Build
        run: |
          cd dlist-web
          pnpm install
          pnpm i18n:build
          pnpm build
          cd ..

      - name: Commit dist
        run: |
          cd web-dist
          rm -rf dist
          cp -r ../dlist-web/dist .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --amend -m "upload dev dist $(date '+%Y-%m-%d %H:%M:%S')"
          git push --force
          cd ..
